/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TudiaRouteImport } from './routes/tudia'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SimRouteImport } from './routes/sim'
import { Route as PremiumSuccessRouteImport } from './routes/premium-success'
import { Route as PremiumProgresoRouteImport } from './routes/premium-progreso'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as GuardadosRouteImport } from './routes/guardados'
import { Route as FrasesRouteImport } from './routes/frases'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EscanerRouteImport } from './routes/escaner'
import { Route as DateRouteImport } from './routes/date'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as AcademiaRouteImport } from './routes/academia'
import { Route as IndexRouteImport } from './routes/index'

const TudiaRoute = TudiaRouteImport.update({
  id: '/tudia',
  path: '/tudia',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SimRoute = SimRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumSuccessRoute = PremiumSuccessRouteImport.update({
  id: '/premium-success',
  path: '/premium-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumProgresoRoute = PremiumProgresoRouteImport.update({
  id: '/premium-progreso',
  path: '/premium-progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardadosRoute = GuardadosRouteImport.update({
  id: '/guardados',
  path: '/guardados',
  getParentRoute: () => rootRouteImport,
} as any)
const FrasesRoute = FrasesRouteImport.update({
  id: '/frases',
  path: '/frases',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EscanerRoute = EscanerRouteImport.update({
  id: '/escaner',
  path: '/escaner',
  getParentRoute: () => rootRouteImport,
} as any)
const DateRoute = DateRouteImport.update({
  id: '/date',
  path: '/date',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaRoute = AcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/ayuda': typeof AyudaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/date': typeof DateRoute
  '/escaner': typeof EscanerRoute
  '/feed': typeof FeedRoute
  '/frases': typeof FrasesRoute
  '/guardados': typeof GuardadosRoute
  '/historial': typeof HistorialRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/premium-progreso': typeof PremiumProgresoRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/sim': typeof SimRoute
  '/sos': typeof SosRoute
  '/tudia': typeof TudiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/ayuda': typeof AyudaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/date': typeof DateRoute
  '/escaner': typeof EscanerRoute
  '/feed': typeof FeedRoute
  '/frases': typeof FrasesRoute
  '/guardados': typeof GuardadosRoute
  '/historial': typeof HistorialRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/premium-progreso': typeof PremiumProgresoRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/sim': typeof SimRoute
  '/sos': typeof SosRoute
  '/tudia': typeof TudiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/ayuda': typeof AyudaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/date': typeof DateRoute
  '/escaner': typeof EscanerRoute
  '/feed': typeof FeedRoute
  '/frases': typeof FrasesRoute
  '/guardados': typeof GuardadosRoute
  '/historial': typeof HistorialRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/premium-progreso': typeof PremiumProgresoRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/sim': typeof SimRoute
  '/sos': typeof SosRoute
  '/tudia': typeof TudiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academia'
    | '/ayuda'
    | '/biblioteca'
    | '/date'
    | '/escaner'
    | '/feed'
    | '/frases'
    | '/guardados'
    | '/historial'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/premium'
    | '/premium-progreso'
    | '/premium-success'
    | '/sim'
    | '/sos'
    | '/tudia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academia'
    | '/ayuda'
    | '/biblioteca'
    | '/date'
    | '/escaner'
    | '/feed'
    | '/frases'
    | '/guardados'
    | '/historial'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/premium'
    | '/premium-progreso'
    | '/premium-success'
    | '/sim'
    | '/sos'
    | '/tudia'
  id:
    | '__root__'
    | '/'
    | '/academia'
    | '/ayuda'
    | '/biblioteca'
    | '/date'
    | '/escaner'
    | '/feed'
    | '/frases'
    | '/guardados'
    | '/historial'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/premium'
    | '/premium-progreso'
    | '/premium-success'
    | '/sim'
    | '/sos'
    | '/tudia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademiaRoute: typeof AcademiaRoute
  AyudaRoute: typeof AyudaRoute
  BibliotecaRoute: typeof BibliotecaRoute
  DateRoute: typeof DateRoute
  EscanerRoute: typeof EscanerRoute
  FeedRoute: typeof FeedRoute
  FrasesRoute: typeof FrasesRoute
  GuardadosRoute: typeof GuardadosRoute
  HistorialRoute: typeof HistorialRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  PremiumProgresoRoute: typeof PremiumProgresoRoute
  PremiumSuccessRoute: typeof PremiumSuccessRoute
  SimRoute: typeof SimRoute
  SosRoute: typeof SosRoute
  TudiaRoute: typeof TudiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tudia': {
      id: '/tudia'
      path: '/tudia'
      fullPath: '/tudia'
      preLoaderRoute: typeof TudiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim': {
      id: '/sim'
      path: '/sim'
      fullPath: '/sim'
      preLoaderRoute: typeof SimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-success': {
      id: '/premium-success'
      path: '/premium-success'
      fullPath: '/premium-success'
      preLoaderRoute: typeof PremiumSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-progreso': {
      id: '/premium-progreso'
      path: '/premium-progreso'
      fullPath: '/premium-progreso'
      preLoaderRoute: typeof PremiumProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardados': {
      id: '/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof GuardadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frases': {
      id: '/frases'
      path: '/frases'
      fullPath: '/frases'
      preLoaderRoute: typeof FrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escaner': {
      id: '/escaner'
      path: '/escaner'
      fullPath: '/escaner'
      preLoaderRoute: typeof EscanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date': {
      id: '/date'
      path: '/date'
      fullPath: '/date'
      preLoaderRoute: typeof DateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia': {
      id: '/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademiaRoute: AcademiaRoute,
  AyudaRoute: AyudaRoute,
  BibliotecaRoute: BibliotecaRoute,
  DateRoute: DateRoute,
  EscanerRoute: EscanerRoute,
  FeedRoute: FeedRoute,
  FrasesRoute: FrasesRoute,
  GuardadosRoute: GuardadosRoute,
  HistorialRoute: HistorialRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  PremiumProgresoRoute: PremiumProgresoRoute,
  PremiumSuccessRoute: PremiumSuccessRoute,
  SimRoute: SimRoute,
  SosRoute: SosRoute,
  TudiaRoute: TudiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
